### ISSUE TITLE
Readme + more documentation?

### ISSUE THREAD

**Issue by sixinli** [davido/gerrit-ci-plugin#6]
Hi,

I have been looking around for a way to report ci status back to gerrit, and this seems to be exactly what I want! However a few pages in the documentation seems to be missing, i.e. https://github.com/davido/gerrit-ci-plugin/blob/master/src/Documentation/database-setup.html returns a 404 :(

I am wondering what's the instruction on setting up the db besides adding the configuration? 

Thanks,
Sixin

**Comment by sixinli** [comment]
also there seems to be more documentation here: https://gerrit.googlesource.com/plugins/verify-status/+/master/src/main/resources/Documentation (not sure if its the same project though since the name is different and there's no explicit indication...)

**Comment by davido** [comment]
Yeah, we changed the name and moved this plugin to: [1]. I see, that you have found it out by yourself already and contributed changes to this plugin: [2].
- [1] https://gerrit-review.googlesource.com/#/admin/projects/plugins/verify-status
- [2] https://gerrit-review.googlesource.com/82952
